# Project metadata - cloud
sonar.organization=nedevski
sonar.projectKey=nedevski_hass_athletic_fitness_bulgaria

# Project metadata - selfhosted instance
# sonar.projectKey=

# Source and test directories
sonar.sources=custom_components/athletic_fitness_bg
sonar.tests=tests

# Python
sonar.python.version = 3.13
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/*.html